graph TD;
    classDef node fill:#eee,stroke:#eee,color:#333
    classDef route fill:#2080D0,stroke:#eee,color:#fff
    classDef nod fill:#C080C0,stroke:#eee,color:#fff
    classDef service fill:#A9C9EB,stroke:#eee,color:#444
    test1_model -- db -->firestore;
    test1_model -- locale -->test1_locale;
    test5_model --> db;
    test5_model -- locale -->test5_locale;
