# add variables here to be used in config as "${VAR}"
$variables:
  PORT: ${{PORT||3000}}
# ---------------------
# 
# services components
# 
# ---------------------
services:
  load: all
  configuration:
    test1:
      upath: test1@app1
    test1_locale:
      upath: locale@nxn/db
      default: en
      langs:
        en: $ref(../locales/en_test1.strings)
    firestore:
      upath: firestore@googleapi
      conPath: .firestore
    test1_model:
      path: "@nxn/db/db_model.service"
      schema: $ref(../models/test1.schema)
      injections:
        db: firestore
        locale: test1_locale
# ---------------------
# 
# express routers
# 
# ---------------------
routes:
  # route default path
  load: "*"
  configuration:
    test1_route:
      upath: test1@app1
      url: /app1/test1
# ---------------------
# 
# to be loaded at startup
# 
# ---------------------
run:
  load: express
# ---------------------
# 
# Tests
# (launched if env TEST=true)
# 
# ---------------------
tests:
  load: express
  configuration:
    test2_test:
      upath: test2@app1
      injections:
        test2: test2
# express middleware section
middleware:
  defaultPath: "@nxn/boot/middleware/$id"
  load: ENV,debug,express,CORS2,JSON
  configuration:
    express:
      port: ${PORT}
      message: Express server run on port
    cors2:
      verbs: GET,POST,PUT,DELETE
    env: {}
    debug:
      path: "@nxn/debug"
      DEBUG: "*"
      DEBUG_COLORS: 1
