graph LR;
subgraph main
    direction LR;

    subgraph Application
        direction LR;
        classDef nodeCls fill:#C080C0,stroke:#eee,color:#fff
        classDef routeCls fill:#2080D0,stroke:#eee,color:#fff
        classDef nodCls fill:#C080C0,stroke:#eee,color:#fff
        classDef serviceCls fill:#A9C9EB,stroke:#eee,color:#444
    test1_route("test1_route"):::routeCls
    test5_route("test5_route"):::routeCls
    test1["test1"]:::serviceCls
    test1_locale["test1_locale"]:::serviceCls
    firestore["firestore"]:::serviceCls
    mysql["mysql"]:::serviceCls
    test4["test4"]:::serviceCls
    test5_locale["test5_locale"]:::serviceCls
    test5_model["test5_model"]:::serviceCls
    test5_model --> db;
    test5_model -- locale -->test5_locale;
    test5["test5"]:::serviceCls
    test1_node["test1_node"]:::nodeCls
end

    subgraph Legend
        Route:::routeCls
        Service:::serviceCls
        Node:::nodCls
    end

end



style Application fill:#fff,stroke:#999,color:#222
style Legend fill:#eee,stroke:#eee,color:#333
style main fill:#eee,stroke:#eee,color:#eee
