modules:
  load: "*"
  configuration:
    generators_mod:
      upath: generators@generators
    config_mod:
      upath: config@config
services:
  load: "*"
  configuration:
    db:
      path: "@nxn/db/firestore.service"
      conPath: .firestore
      description: Firestore

