graph LR;
subgraph main
    direction LR;

    subgraph Application
        direction LR;
        classDef nodeCls fill:#C080C0,stroke:#eee,color:#fff
        classDef routeCls fill:#2080D0,stroke:#eee,color:#fff
        classDef nodCls fill:#C080C0,stroke:#eee,color:#fff
        classDef serviceCls fill:#A9C9EB,stroke:#eee,color:#444
    generate_route("generate_route"):::routeCls
    generate_route -- service -->generate;
    db[("db")]:::serviceCls
    mermaid["mermaid"]:::serviceCls
    model["model"]:::serviceCls
    generate["generate"]:::serviceCls
    generate -- model -->model;
    generate -- module -->module;
    module["module"]:::serviceCls
    config_locale["config_locale"]:::serviceCls
    config_model(/"config_model"/):::serviceCls
    config_model --> db;
    config_model -- locale -->config_locale;
    config["config"]:::serviceCls
end

    subgraph Legend
        Route:::routeCls
        Service:::serviceCls
        Node:::nodCls
    end

end



style Application fill:#fff,stroke:#999,color:#222
style Legend fill:#eee,stroke:#eee,color:#333
style main fill:#eee,stroke:#eee,color:#eee
