# add variables here to be used in config as "${VAR}"
$variables:
  PORT: ${{PORT||3000}}

# ---------------------
#
#   services components
#
# ---------------------
services:
  load: 'all'
  configuration:

# ---------------------
#
# express routers
#
# ---------------------
routes:
  # route default path
  load: '*'
  configuration:

# ---------------------
#
# to be loaded at startup
#
# ---------------------
run:
  load: express

# ---------------------
#
# Tests 
# (launched if env TEST=true)
#
# ---------------------
tests:
  load: express

# express middleware section
middleware:
  defaultPath: "@nxn/boot/middleware/$id"
  load: ENV,debug,express,CORS2,JSON
  configuration:
    express:
      port: "${PORT}"
      message: Express server run on port
    cors2:
      verbs: GET,POST,PUT,DELETE
    env: {}
    debug:
      path: "@nxn/debug"
      DEBUG: "*"
      DEBUG_COLORS: 1
